### ISSUE TITLE
Plugin forces homebridge to terminate

### ISSUE THREAD

**Issue by jordangoody** [SeydX/homebridge-star-projector#9]
A few weeks ago my home bridge wouldn't respond and I discovered this in the logs. I miss asking my projector to turn on. Please help!

Error: Error from socket: connect EHOSTUNREACH 192.168.7.243:6668 - Local (192.168.7.46:59685)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-star-projector/node_modules/tuyapi/index.js:528:30)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by lee7578kimo** [comment]
Got similar error, too.

[12/28/2022, 1:02:28 AM] [StarProjector] Restarting Process...
[12/28/2022, 1:02:28 AM] [StarProjector] Launched child bridge with PID 28335
[12/28/2022, 1:02:28 AM] Registering platform 'homebridge-star-projector.StarProjector'
[12/28/2022, 1:02:28 AM] [StarProjector] Loaded homebridge-star-projector v1.0.6 child bridge successfully
[12/28/2022, 1:02:28 AM] Loaded 1 cached accessories from cachedAccessories.0E0A67E9311B.
[12/28/2022, 1:02:28 AM] [StarProjector] Nordeco 極光星空燈: Configuring accessory...
[12/28/2022, 1:02:28 AM] Homebridge v1.6.0 (HAP v0.11.0) (StarProjector) is running on port 51024.

/homebridge/node_modules/homebridge-star-projector/node_modules/tuyapi/index.js:627
      this.emit('error', new Error('Error from socket: ' + err.message));
                         ^
Error: Error from socket: connect EHOSTUNREACH 192.168.1.14:6668
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-star-projector/node_modules/tuyapi/index.js:627:26)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[12/28/2022, 1:02:35 AM] [StarProjector] Child bridge process ended
[12/28/2022, 1:02:35 AM] [StarProjector] Process Ended. Code: 1, Signal: null

**Comment by 4rft5** [comment]
just got this error today too, any possible fix?

Error: Error from socket: connect EHOSTUNREACH 192.168.6.7:6668
    at Socket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-star-projector/node_modules/tuyapi/index.js:528:30)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by custa1200** [comment]
I am also getting errors 

20/2/2023, 10:57:58 amStar Projector BridgeERRORError: Error from socket: connect EHOSTUNREACH 192.168.1.16:6668
    at Socket.<anonymous> (/var/lib/hoobs/starprojectorbridge/node_modules/tuyapi/index.js:528:30)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
